spring:
  profiles:
    active: development

  main:
    allow-circular-references: true

  mail:
    host: smtp.office365.com
    port: 587
    username: civcic.ognjen98@outlook.com
    password: itachiuchiha-98
    properties:
      mail:
        store:
          protocol: pop3
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${JDBC_ISA_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always

  jpa:
#    properties:
#      hibernate:
#        globally-quoted-identifiers: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8082
