spring:
  profiles:
    active: development

  mail:
    host: smtp.gmail.com
    port: 587
    username: isaglobalpharmacy@gmail.com
    password: Pharmacy123456!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${JDBC_ISA_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8082